const SET_USER = 'SET_USER'
const TOGGLE_RESULTS_FLAG = 'TOGGLE_RESULTS_FLAG'
const SET_RESULTS_FLAG = 'SET_RESULTS_FLAG'

export default {
    SET_USER,
    SET_RESULTS_FLAG,
    TOGGLE_RESULTS_FLAG
}
